services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - aidea:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidea
    networks:
      - aidea
    ports:
      - "0:5432"
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - aidea:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - aidea

networks:
  aidea:
    driver: bridge

volumes:
  aidea:
