export const actionTypes = {
  FETCH_IDEAS: 'FETCH_IDEAS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  ADD_IDEA: 'ADD_IDEA',
  UPVOTE_IDEA: 'UPVOTE_IDEA',
  DOWNVOTE_IDEA: 'DOWNVOTE_IDEA',
  LOADING: 'LOADING',
  LOADED: 'LOADED'
}
