export const appStates = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
  ERROR: 'ERROR'
}

export const actionTypes = {
  FETCH_IDEAS: 'FETCH_IDEAS',
  FETCH_IDEAS_SUCCESS: 'FETCH_IDEAS_SUCCESS',
  FETCH_IDEAS_ERROR: 'FETCH_IDEAS_ERROR',
  ADD_IDEA: 'ADD_IDEA',
  UPVOTE_IDEA: 'UPVOTE_IDEA',
  DOWNVOTE_IDEA: 'DOWNVOTE_IDEA',
  IDEA_UPDATED: 'IDEA_UPDATED'
}
