name: 🚀 Deploy >> Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🏗 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: ⬇️ Install Vercel CLI
        run: npm add --g vercel@latest

      - name: ⬇️ Pull Vercel Env
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🏗 Build
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ⬆️ Deploy
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
